Repository ecamp/ecamp3, pull requests merged in 2023-12, with the labels that each got.

#4191 Richtext popup: show list formatting ability and improve design
  frontend/src/components/form/tiptap/TiptapEditor.vue
  frontend/src/components/form/tiptap/TiptapToolbarButton.vue
  frontend/src/scss/global.scss
Labels: type: Frontend, UX/UI, deploy!, External feedback

#4027 Add rumantsch
  api/.env
  api/.env.test
  api/src/Entity/Languages.php
  api/src/Entity/Profile.php
  api/src/Service/MailService.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testOpenApiSpecMatchesSnapshot__1.yml
  api/tests/Integration/Serializer/Normalizer/TranslationConstraintViolationListNormalizerIntegrationTest.php
  api/tests/Service/MailServiceTest.php
  api/translations/validators.rm.yml
  api/translations/validators.rm_CH_scout.yml
  common/locales/rm-CH-scout.json
  common/locales/rm.json
  frontend/src/helpers/__tests__/serverError.spec.js
  frontend/src/locales/rm-CH-scout.json
  frontend/src/locales/rm.json
  frontend/src/plugins/i18n/__tests__/apiFallbackLocalesFor.spec.js
  frontend/src/plugins/i18n/apiFallbackLocalesFor.js
  frontend/src/plugins/i18n/index.js
  print/locales/rm-CH-scout.json
  print/locales/rm.json
  print/locales/vueI18nConfig.js
Labels: deploy!

#3993 Copy & paste activity
  api/src/Entity/Activity.php
  api/src/State/ActivityCreateProcessor.php
  api/tests/Api/Activities/CreateActivityTest.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testOpenApiSpecMatchesSnapshot__1.yml
  api/tests/State/ActivityCreateProcessorTest.php
  frontend/src/components/activity/CopyActivityInfoDialog.vue
  frontend/src/components/activity/ScheduleEntry.vue
  frontend/src/components/collaborator/PromptCollaboratorDeactivate.vue
  frontend/src/components/program/DialogActivityCreate.vue
  frontend/src/components/program/DialogActivityForm.vue
  frontend/src/components/program/picasso/PicassoEntry.vue
  frontend/src/components/prompt/PopoverPrompt.vue
  frontend/src/components/prompt/PromptEntityDelete.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
Labels: deploy!

#4202 Activity view: implement day switcher in sidebar
  frontend/src/components/activity/DaySwitcher.vue
  frontend/src/components/generic/AvatarRow.vue
  frontend/src/components/program/picasso/DayResponsibles.vue
  frontend/src/components/program/picasso/Picasso.vue
  frontend/src/router.js
  frontend/src/scss/global.scss
  frontend/src/views/activity/SideBarProgram.vue
Labels: type: Frontend, UX/UI, deploy!

#4162 Camp create: choose prototype UX improvement
  frontend/package.json
  frontend/src/components/buttons/ButtonContinue.vue
  frontend/src/components/campCreate/CampCreate.vue
  frontend/src/components/campCreate/CampCreateStep1.vue
  frontend/src/components/campCreate/CampCreateStep2.vue
  frontend/src/components/form/base/ESelect.vue
  frontend/src/components/layout/ContentActions.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/scss/global.scss
  frontend/src/views/CampCreate.vue
Labels: type: Frontend, UX/UI, deploy!, External feedback

#4268 Fix error messages not visible in activity view
  frontend/src/components/activity/CardContentNode.vue
  frontend/src/components/activity/content/LAThematicArea.vue
  frontend/src/components/activity/content/Notes.vue
  frontend/src/components/activity/content/SafetyConcept.vue
  frontend/src/components/activity/content/Storyboard.vue
  frontend/src/components/activity/content/Storycontext.vue
  frontend/src/components/activity/content/storyboard/StoryboardRowDefault.vue
  frontend/src/components/activity/content/storyboard/StoryboardRowDense.vue
  frontend/src/components/material/MaterialTable.vue
  frontend/src/scss/global.scss
Labels: deploy!

#4131 Switch from coveralls npm dependency to universal coverage reporter
  .github/workflows/continuous-integration.yml
  frontend/package-lock.json
  frontend/package.json
Labels: Blocks others

#4342 fix(frontend): downgrade vue to 2.7.15
  frontend/package-lock.json
  frontend/package.json
  renovate.json
Labels: deploy!

#4303 Improve design of layout content nodes in layout mode
  common/locales/de.json
  common/locales/en.json
  common/locales/fr.json
  common/locales/it.json
  frontend/src/assets/icons/ColumnLayout.svg
  frontend/src/assets/icons/ResponsiveLayout.svg
  frontend/src/components/activity/ButtonNestedContentNodeAdd.vue
  frontend/src/components/activity/ContentNode.vue
  frontend/src/components/activity/DraggableContentNodes.vue
  frontend/src/components/activity/MenuCardlessContentNode.vue
  frontend/src/components/activity/ScheduleEntry.vue
  frontend/src/components/activity/content/ColumnLayout.vue
  frontend/src/components/activity/content/LAThematicArea.vue
  frontend/src/components/activity/content/Material.vue
  frontend/src/components/activity/content/Notes.vue
  frontend/src/components/activity/content/ResponsiveLayout.vue
  frontend/src/components/activity/content/SafetyConcept.vue
  frontend/src/components/activity/content/Storyboard.vue
  frontend/src/components/activity/content/Storycontext.vue
  frontend/src/components/activity/content/columnLayout/ColumnIndicator.vue
  frontend/src/components/activity/content/columnLayout/MobileColumnWidthIndicator.vue
  frontend/src/components/activity/content/columnLayout/ResizableColumn.vue
  frontend/src/components/activity/content/columnLayout/ResizableColumnHeader.vue
  frontend/src/components/activity/content/layout/ContentNodeCard.vue
  frontend/src/components/activity/content/layout/LayoutCard.vue
  frontend/src/components/activity/content/layout/LayoutNodeCard.vue
  frontend/src/components/activity/content/storyboard/StoryboardRowDefault.vue
  frontend/src/components/activity/content/storyboard/StoryboardRowDense.vue
  frontend/src/components/material/MaterialTable.vue
  frontend/src/plugins/vuetify.js
  frontend/src/scss/global.scss
Labels: type: Frontend, UX/UI, deploy!

#4347 chore(print): use css @page landscape instead of content rotation
  print/assets/print-preview.css
  print/components/PicassoChunk.vue
Labels: deploy!
