Repository ecamp/ecamp3, pull requests merged in 2023-06, with the labels that each got.

#3491 Fix react printing nested enumeration lists
  frontend/src/components/print/print-react/components/RichText.jsx
Labels: deploy!

#3494 generatePdfMixin.js: report react-print errors to sentry
  frontend/src/components/print/print-react/generatePdfMixin.js
Labels: deploy!

#3495 fix(print): various bug fixes
  frontend/src/components/print/print-nuxt/generatePdfMixin.js
  print/components/PicassoChunk.vue
  print/layouts/default.vue
  print/nuxt.config.js
  print/server-middleware/routes/pdfGeneratorNativeChrome.js
Labels: deploy!

#3524 show timing while resizing, moving, creating
  common/helpers/dateHelperUTCFormatted.js
  frontend/src/components/program/picasso/Picasso.vue
  frontend/src/components/program/picasso/PicassoEntry.vue
  frontend/src/components/program/picasso/useDragAndDropMove.js
  frontend/src/components/program/picasso/useDragAndDropResize.js
  frontend/src/mixins/dateHelperUTCFormatted.js
Labels: deploy!

#3507 Picasso splitting and cropping in print
  common/helpers/__tests__/picasso.spec.js
  common/helpers/picasso.js
  frontend/src/components/print/PrintConfigurator.vue
  frontend/src/components/print/print-react/components/picasso/DayColumn.jsx
  frontend/src/components/print/print-react/components/picasso/Picasso.jsx
  frontend/src/components/print/print-react/components/picasso/PicassoPage.jsx
  frontend/src/components/print/print-react/components/picasso/longestTime.js
  frontend/src/components/print/print-react/documents/campPrint/Component.jsx
  frontend/vite.config.js
  print/components/PicassoPeriod.vue
Labels: deploy!

#3405 ActivityProgressLabel: /api & campAdmin
  api/fixtures/activities.yml
  api/fixtures/activity-progress-labels.yml
  api/migrations/schema/Version20230408180319.php
  api/migrations/schema/Version20230409164830.php
  api/migrations/schema/Version20230502191133.php
  api/src/Entity/Activity.php
  api/src/Entity/ActivityProgressLabel.php
  api/src/Entity/Camp.php
  api/src/Repository/ActivityProgressLabelRepository.php
  api/tests/Api/Activities/CreateActivityTest.php
  api/tests/Api/ActivityProgressLabel/CreateActivityProgressLabelTest.php
  api/tests/Api/ActivityProgressLabel/DeleteActivityProgressLabelTest.php
  api/tests/Api/ActivityProgressLabel/ListActivityProgressLabelTest.php
  api/tests/Api/ActivityProgressLabel/ReadActivityProgressLabelTest.php
  api/tests/Api/ActivityProgressLabel/UpdateActivityProgressLabelTest.php
  common/locales/de.json
  common/locales/en.json
  common/locales/fr.json
  common/locales/it.json
  frontend/src/components/activity/ScheduleEntry.vue
  frontend/src/components/campAdmin/CampActivityProgressLabels.vue
  frontend/src/components/campAdmin/DialogActivityProgressLabelCreate.vue
  frontend/src/components/campAdmin/DialogActivityProgressLabelEdit.vue
  frontend/src/components/campAdmin/DialogActivityProgressLabelForm.vue
  frontend/src/components/dashboard/ActivityRow.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/views/camp/Admin.vue
  frontend/src/views/camp/Dashboard.vue
  frontend/src/views/camp/__tests__/Admin.spec.js
Labels: deploy!

#3520 Bugfix: Apply the user's selected locale after normal login
  frontend/src/views/auth/Login.vue
Labels: deploy!

#3545 Adjust accept page according to new illustration concept
  frontend/src/assets/invitation/edge-left.svg
  frontend/src/assets/invitation/edge-right.svg
  frontend/src/assets/invitation/tree-left.svg
  frontend/src/assets/invitation/tree-right.svg
  frontend/src/assets/tents/TentDay.svg
  frontend/src/components/buttons/ButtonBack.vue
  frontend/src/components/navigation/UserMeta.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/plugins/vuetify.js
  frontend/src/router.js
  frontend/src/scss/global.scss
  frontend/src/views/Camps.vue
  frontend/src/views/camp/Invitation.vue
  frontend/src/views/camp/InvitationRejected.vue
  frontend/src/views/camp/InvitationUpdateError.vue
Labels: type: Frontend, UX/UI, deploy!

#3552 Period: do not fetch ContentNodes
  api/src/Entity/Period.php
  api/tests/Entity/PeriodTest.php
Labels: performance

#3461 Only open pickers when clicking the picker button
  frontend/src/components/form/base/BasePicker.vue
  frontend/src/components/form/base/EColorPicker.vue
  frontend/src/components/form/base/__tests__/EColorPicker.spec.js
  frontend/src/components/form/base/__tests__/EDatePicker.spec.js
  frontend/src/components/form/base/__tests__/ETimePicker.spec.js
Labels: deploy!

#3526 print: Optimize nuxt design
  e2e/specs/nuxtPrint.cy.js
  e2e/specs/reactPrint.cy.js
  e2e/tasks/moveDownloads.js
  frontend/src/components/print/PrintConfigurator.vue
  print/assets/variables.scss
  print/components/PicassoChunk.vue
  print/components/ProgramPeriod.vue
  print/components/config/Cover.vue
  print/components/generic/CategoryLabel.vue
  print/components/generic/CheckMark.vue
  print/components/scheduleEntry/ScheduleEntry.vue
  print/components/scheduleEntry/contentNode/ColumnLayout.vue
  print/components/scheduleEntry/contentNode/ColumnLayoutColumn.vue
  print/components/scheduleEntry/contentNode/ContentNodeContent.vue
  print/components/scheduleEntry/contentNode/LAThematicArea.vue
  print/components/scheduleEntry/contentNode/Material.vue
  print/components/scheduleEntry/contentNode/Storyboard.vue
  print/components/story/StoryDay.vue
  print/components/story/StoryPeriod.vue
  print/layouts/default.vue
  print/pages/index.vue
  print/server-middleware/routes/pdfGeneratorNativeChrome.js
  print/static/fonts/inter/InterDisplay-Black.otf
  print/static/fonts/inter/InterDisplay-BlackItalic.otf
  print/static/fonts/inter/InterDisplay-Bold.otf
  print/static/fonts/inter/InterDisplay-BoldItalic.otf
  print/static/fonts/inter/InterDisplay-ExtraBold.otf
  print/static/fonts/inter/InterDisplay-ExtraBoldItalic.otf
  print/static/fonts/inter/InterDisplay-ExtraLight.otf
  print/static/fonts/inter/InterDisplay-ExtraLightItalic.otf
  print/static/fonts/inter/InterDisplay-Italic.otf
  print/static/fonts/inter/InterDisplay-Light.otf
  print/static/fonts/inter/InterDisplay-LightItalic.otf
  print/static/fonts/inter/InterDisplay-Medium.otf
  print/static/fonts/inter/InterDisplay-MediumItalic.otf
  print/static/fonts/inter/InterDisplay-Regular.otf
  print/static/fonts/inter/InterDisplay-SemiBold.otf
  print/static/fonts/inter/InterDisplay-SemiBoldItalic.otf
  print/static/fonts/inter/InterDisplay-Thin.otf
  print/static/fonts/inter/InterDisplay-ThinItalic.otf
  print/static/fonts/inter/inter.css
  print/tailwind.config.js
Labels: type: Print, UX/UI, deploy!

#3558 Use new illustration style for 404 page
  frontend/src/assets/tents/ShootingStar.vue
  frontend/src/assets/tents/TentNight.vue
  frontend/src/assets/tents/stars.svg
  frontend/src/components/navigation/UserMeta.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/scss/global.scss
  frontend/src/views/Camps.vue
  frontend/src/views/PageNotFound.vue
Labels: type: Frontend, UX/UI, deploy!

#3580 chore: add filter to query for all dayResponsibles of a period
  api/src/Entity/DayResponsible.php
  api/src/Entity/Period.php
  api/tests/Api/Periods/ReadPeriodTest.php
  common/helpers/__tests__/dayResponsibles.spec.js
  common/helpers/dayResponsibles.js
  frontend/src/components/print/print-react/components/picasso/DayHeader.jsx
  frontend/src/components/print/print-react/components/picasso/PicassoPage.jsx
  frontend/src/components/print/print-react/documents/campPrint/index.js
  print/components/PicassoChunk.vue
  print/components/PicassoPeriod.vue
Labels: deploy!

#3598 french translations
  common/locales/fr-CH-scout.json
  common/locales/fr.json
  frontend/src/locales/fr-CH-scout.json
  frontend/src/locales/fr.json
Labels: deploy!

#3596 Fix list spacing in nuxt print
  print/tailwind.config.js
Labels: deploy!

#3586 Move change button inside readonly text-field
  frontend/src/scss/global.scss
  frontend/src/views/Profile.vue
Labels: UX/UI, deploy!
