Repository ecamp/ecamp3, pull requests merged in 2023-10, with the labels that each got.

#3894 Optimize material table in small container
  frontend/src/components/activity/content/Storyboard.vue
  frontend/src/components/material/MaterialTable.vue
Labels: deploy!

#3841 Organize admin views
  e2e/specs/clientPrint.cy.js
  e2e/specs/nuxtPrint.cy.js
  frontend/src/components/campAdmin/CampConditionalFields.vue
  frontend/src/components/campAdmin/CampDangerZone.vue
  frontend/src/components/campAdmin/DialogMaterialListEdit.vue
  frontend/src/components/generic/GenericPage.vue
  frontend/src/components/layout/ContentGroup.vue
  frontend/src/components/layout/SidebarListItem.vue
  frontend/src/components/material/MaterialListsEdit.vue
  frontend/src/components/navigation/SideBar.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/router.js
  frontend/src/views/admin/Activity.vue
  frontend/src/views/admin/Collaborators.vue
  frontend/src/views/admin/Info.vue
  frontend/src/views/admin/MaterialLists.vue
  frontend/src/views/admin/Print.vue
  frontend/src/views/admin/SideBarAdmin.vue
  frontend/src/views/admin/__tests__/Admin.spec.js
  frontend/src/views/camp/navigation/desktop/NavTopbar.vue
  frontend/src/views/camp/navigation/mobile/NavSidebar.vue
  frontend/src/views/material/MaterialDetail.vue
Labels: type: Frontend, UX/UI, deploy!

#3873 fix(frontend): fix auto-save; improve Controls page
  frontend/src/components/form/api/ApiWrapper.vue
  frontend/src/views/dev/Controls.vue
Labels: deploy!

#3842 replace mailhog with maildev
  .helm/ecamp3/templates/mail_deployment.yaml
  .helm/ecamp3/values.yaml
  api/docker/caddy/Caddyfile
  docker-compose.yml
Labels: deploy!

#3962 FIX: variant has been renamed to isDefaultVariant
  frontend/src/components/material/MaterialTable.vue
Labels: Bug

#3964 Vertically center text across fields and heights on baseline
  frontend/src/components/form/tiptap/VTiptapEditor.vue
  frontend/src/views/dev/Controls.vue
Labels: deploy!

#3996 frontend: fix mobile view of materialLists
  frontend/src/components/material/MaterialLists.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/router.js
  frontend/src/views/admin/AdminMaterialLists.vue
  frontend/src/views/camp/navigation/mobile/NavBottombar.vue
  frontend/src/views/material/MaterialLists.vue
Labels: deploy!

#4000 make ready for go live
  .github/workflows/reusable-dev-deployment.yml
  .github/workflows/reusable-stage-prod-deployment.yml
  .helm/ecamp3/templates/api_deployment.yaml
  .helm/ecamp3/templates/api_secrets.yaml
  .helm/ecamp3/values.yaml
  api/.env
  api/config/services.yaml
  api/fixtures/camps.yml
  api/migrations/schema/Version20231021145933.php
  api/src/Controller/CouponKeyController.php
  api/src/Entity/Camp.php
  api/src/Service/CampCouponService.php
  api/src/State/CampCreateProcessor.php
  api/src/Validator/Camp/AssertValidCouponKey.php
  api/src/Validator/Camp/AssertValidCouponKeyValidator.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testOpenApiSpecMatchesSnapshot__1.yml
  api/tests/Integration/Service/CampCouponServiceTest.php
  api/tests/State/CampCreateProcessorTest.php
  common/locales/de.json
  common/locales/en.json
  common/locales/fr.json
  common/locales/it.json
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/views/CampCreate.vue
  frontend/src/views/auth/Login.vue
Labels: deploy!

#3870 On delete ScheduleEntry, lock Activity
  api/src/Entity/Activity.php
  api/src/Validator/AssertLastCollectionItemIsNotDeleted.php
  api/src/Validator/AssertLastCollectionItemIsNotDeletedValidator.php
  api/tests/Api/ScheduleEntries/DeleteScheduleEntryTest.php
  api/tests/Validator/AssertEitherIsNullValidatorTest.php
  api/tests/Validator/AssertLastCollectionItemIsNotDeletedValidatorTest.php
  api/translations/validators.de.yml
  api/translations/validators.en.yml
  api/translations/validators.fr.yml
  api/translations/validators.it.yml
Labels: deploy!

#4006 Optimize column layout experience
  frontend/src/components/activity/CardContentNode.vue
  frontend/src/components/activity/ContentNode.vue
  frontend/src/components/activity/DraggableContentNodes.vue
  frontend/src/components/activity/MenuCardlessContentNode.vue
  frontend/src/components/activity/ScheduleEntry.vue
  frontend/src/components/activity/content/ColumnLayout.vue
  frontend/src/components/activity/content/Material.vue
  frontend/src/components/activity/content/Notes.vue
  frontend/src/components/activity/content/SafetyConcept.vue
  frontend/src/components/activity/content/Storyboard.vue
  frontend/src/components/activity/content/Storycontext.vue
  frontend/src/components/activity/content/columnLayout/ResizableColumn.vue
  frontend/src/components/activity/content/columnLayout/ResizableColumnHeader.vue
  frontend/src/components/activity/content/layout/LayoutCard.vue
  frontend/src/components/activity/content/layout/LayoutItem.vue
  frontend/src/components/activity/content/storyboard/StoryboardDialogRemoveSection.vue
  frontend/src/components/activity/content/storyboard/StoryboardRowDefault.vue
  frontend/src/components/activity/content/storyboard/StoryboardRowDense.vue
  frontend/src/components/activity/content/storyboard/StoryboardSortable.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/scss/global.scss
Labels: UX/UI, deploy!
