Repository ecamp/ecamp3, pull requests merged in 2024-01, with the labels that each got.

#4350 Replace colorpicker icon with ColorSwatch
  frontend/src/components/form/base/BasePicker.vue
  frontend/src/components/form/base/ColorPicker/ColorSwatch.vue
  frontend/src/components/form/base/EColorPicker.vue
  frontend/src/components/form/base/__tests__/__snapshots__/EColorPicker.spec.js.snap
Labels: type: Frontend, UX/UI, deploy!

#4365 Improve dashboard loading
  frontend/src/components/dashboard/ActivityRow.vue
  frontend/src/components/generic/CategoryChip.vue
  frontend/src/helpers/querySyncHelper.js
  frontend/src/views/camp/Dashboard.vue
Labels: type: Frontend, UX/UI, deploy!, Performance, test-flaky-e2e!

#4366 Hide Materialfilter PeriodOnly in ContentNode #4361
  frontend/src/components/activity/content/Material.vue
  frontend/src/components/material/MaterialTable.vue
Labels: deploy!

#4362 Improve admin activity section
  frontend/src/components/activity/DraggableContentNodes.vue
  frontend/src/components/activity/ScheduleEntry.vue
  frontend/src/components/activity/TogglePaperSize.vue
  frontend/src/components/activity/content/layout/ContentNodeCard.vue
  frontend/src/components/activity/useDisplaySize.js
  frontend/src/components/campAdmin/CampActivityProgressLabels.vue
  frontend/src/components/campAdmin/CampCategories.vue
  frontend/src/components/campAdmin/DialogActivityProgressLabelCreate.vue
  frontend/src/components/campAdmin/DialogActivityProgressLabelEdit.vue
  frontend/src/components/campAdmin/DialogCategoryCreate.vue
  frontend/src/components/campAdmin/DialogCategoryEdit.vue
  frontend/src/components/campAdmin/DialogMaterialListCreate.vue
  frontend/src/components/campAdmin/DialogPeriodCreate.vue
  frontend/src/components/campAdmin/ErrorExistingActivitiesList.vue
  frontend/src/components/category/CategoryProperties.vue
  frontend/src/components/category/CategoryTemplate.vue
  frontend/src/components/dialog/DialogBase.vue
  frontend/src/components/dialog/DialogEntityDelete.vue
  frontend/src/components/form/api/ApiSortable.vue
  frontend/src/components/prompt/PopoverPrompt.vue
  frontend/src/components/prompt/PromptEntityDelete.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/locales/rm.json
  frontend/src/router.js
  frontend/src/scss/global.scss
  frontend/src/views/activity/Category.vue
  frontend/src/views/category/Category.vue
  frontend/src/views/category/SideBarCategory.vue
Labels: type: Frontend, UX/UI, deploy!, External feedback

#4349 Improve alert and popover style
  frontend/src/components/prompt/PopoverPrompt.vue
  frontend/src/scss/global.scss
Labels: type: Frontend, UX/UI, deploy!

#4328 Reduce impact of ApiColorPicker emit bug
  frontend/src/components/form/api/ApiColorPicker.vue
  frontend/src/components/form/base/BasePicker.vue
Labels: Bug, deploy!

#4413 frontend: report Errors to Sentry in print-nuxt/generatePdfMixin.js
  frontend/src/components/print/print-nuxt/generatePdfMixin.js
Labels: deploy!

#4397 Implement simple link decoration in richtext fields
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/form/base/__tests__/__snapshots__/ETextArea.spec.js.snap
  frontend/src/components/form/tiptap/AutoLinkDecoration.js
  frontend/src/components/form/tiptap/TiptapEditor.vue
  frontend/vite.config.js
Labels: Feature request, type: Frontend, deploy!, External feedback

#4422 Disable Sentry session tracking
  frontend/src/main.js
  print/server/plugin/sentry.ts
Labels: deploy!

#4399 frontend: update xlsx to 0.20.1
  frontend/package-lock.json
  frontend/package.json
Labels: deploy!

#4513 Fix schedule entry request loop if no access or typo
  frontend/src/router.js
Labels: Bug, deploy!

#4521 fix(api): mitigate slow queries
  api/src/Doctrine/Filter/ContentNodePeriodFilter.php
  api/src/Repository/FiltersByCampCollaboration.php
  api/tests/Api/ContentNodes/ContentNode/ListContentNodesTest.php
  api/tests/Doctrine/Filter/ContentNodePeriodFilterTest.php
Labels: deploy!

#4546 Display content node instance name in delete dialog
  frontend/src/components/activity/MenuCardlessContentNode.vue
  frontend/src/components/activity/content/layout/ContentNodeCard.vue
Labels: deploy!

#4551 Make progress label clearable
  frontend/src/components/activity/ScheduleEntry.vue
Labels: deploy!
