Repository ecamp/ecamp3, pull requests merged in 2024-09, with the labels that each got.

#5460 Frontend checklist implementation
  .github/workflows/reusable-dev-deployment.yml
  .helm/deploy-to-cluster.sh
  .helm/ecamp3/templates/frontend_configmap.yaml
  .helm/ecamp3/values.yaml
  api/src/Entity/ChecklistItem.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testOpenApiSpecMatchesSnapshot__1.yml
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testRootEndpointMatchesSnapshot__1.json
  common/locales/de.json
  common/locales/en.json
  common/locales/fr.json
  frontend/src/components/activity/ButtonNestedContentNodeAdd.vue
  frontend/src/components/activity/ContentNode.vue
  frontend/src/components/activity/content/Checklist.vue
  frontend/src/components/activity/content/checklist/ChecklistItem.vue
  frontend/src/components/checklist/ChecklistCreate.vue
  frontend/src/components/checklist/ChecklistItemCreate.vue
  frontend/src/components/checklist/ChecklistItemEdit.vue
  frontend/src/components/checklist/SortableChecklist.vue
  frontend/src/components/checklist/SortableChecklistItem.vue
  frontend/src/environment.js
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/router.js
  frontend/src/views/admin/Checklists.vue
  frontend/src/views/admin/SideBarAdmin.vue
  frontend/src/views/checklist/Checklist.vue
  frontend/src/views/checklist/SideBarChecklist.vue
Labels: deploy!

#5914 Fix missing newline escape
  .github/workflows/reusable-dev-deployment.yml
Labels: Bug, Blocks others

#6022 checklist item maximal nesting of 3
  api/fixtures/checklistItems.yml
  api/src/Entity/ChecklistItem.php
  api/tests/Api/ChecklistItems/CreateChecklistItemTest.php
  api/tests/Api/ChecklistItems/ListChecklistItemTest.php
  api/tests/Api/ChecklistItems/UpdateChecklistItemTest.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetCollectionMatchesStructure with data set checklist_items__1.json
Labels: deploy!

#6029 Admin UI adjustment
  frontend/src/assets/eCampLogo.svg
  frontend/src/assets/tents/TentDay.svg
  frontend/src/components/campAdmin/CampMaterialLists.vue
  frontend/src/components/campAdmin/CampMaterialListsItem.vue
  frontend/src/components/checklist/ChecklistOverview.vue
  frontend/src/views/admin/Checklist.vue
  frontend/src/views/admin/Checklists.vue
  frontend/src/views/admin/Debug.vue
  frontend/src/views/admin/SideBarAdmin.vue
  frontend/src/views/camp/Admin.vue
Labels: UX/UI, deploy!

#6039 fix: revert react-pdf to v3
  frontend/package-lock.json
  frontend/package.json
  pdf/package-lock.json
  pdf/package.json
Labels: Blocks others

#6042 fix translation-keys
  frontend/src/views/auth/Register.vue
  frontend/src/views/auth/ResendActivation.vue
  frontend/src/views/auth/ResetPassword.vue
  frontend/src/views/auth/ResetPasswordRequest.vue
Labels: deploy!

#6040 feat(print): render checklists in react pdf
  pdf/src/campPrint/scheduleEntry/contentNode/Checklist.vue
  pdf/src/campPrint/scheduleEntry/contentNode/ContentNode.vue
  pdf/src/prepareInMainThread.js
Labels: deploy!

#6041 Fix checklist ui bugs
  frontend/src/components/activity/content/Checklist.vue
  frontend/src/components/checklist/SortableChecklist.vue
  frontend/src/components/dialog/DialogBottomSheet.vue
Labels: deploy!

#6047 Make checklist contendnode respect acl
  frontend/src/components/activity/content/Checklist.vue
  frontend/src/components/activity/content/checklist/ChecklistItems.vue
Labels: deploy!

#6045 feat(print): activity list implementation for react print
  frontend/eslint.config.mjs
  pdf/eslint.config.mjs
  pdf/src/CampPrint.vue
  pdf/src/campPrint/activityList/ActivityList.vue
  pdf/src/campPrint/activityList/ActivityListPeriod.vue
  pdf/src/campPrint/activityList/ActivityListScheduleEntry.vue
  pdf/src/campPrint/scheduleEntry/InstanceName.vue
  pdf/src/campPrint/scheduleEntry/ScheduleEntry.vue
  pdf/src/campPrint/scheduleEntry/ScheduleEntryTitle.vue
  pdf/src/campPrint/scheduleEntry/contentNode/Checklist.vue
  pdf/src/renderer/__tests__/__snapshots__/program.spec.json.snap
  pdf/src/renderer/__tests__/__snapshots__/single_activity.spec.json.snap
  pdf/src/renderer/__tests__/__snapshots__/single_activity_with_special_text_with_empty_lists.spec.json.snap
  print/eslint.config.mjs
Labels: deploy!
