Repository ecamp/ecamp3, pull requests merged in 2024-06, with the labels that each got.

#5123 chore: change from php-fpm to frankenphp
  .caddy/config-cache/.gitkeep
  .caddy/data/.gitkeep
  .caddy/php-socket/.gitkeep
  .github/workflows/reusable-build-and-push.yml
  .github/workflows/reusable-dev-deployment.yml
  .github/workflows/reusable-e2e-tests-build.yml
  .github/workflows/reusable-e2e-tests-run.yml
  .github/workflows/reusable-stage-prod-deployment.yml
  .helm/build-images.sh
  .helm/deploy-to-cluster.sh
  .helm/ecamp3/templates/api_configmap.yaml
  .helm/ecamp3/templates/api_deployment.yaml
  .helm/ecamp3/templates/api_secrets.yaml
  .helm/ecamp3/templates/hook_db_create.yaml
  .helm/ecamp3/templates/hook_db_drop.yaml
  .helm/ecamp3/templates/hook_db_migrate.yaml
  .helm/ecamp3/values.yaml
  .vscode/launch.json
  api/.dockerignore
  api/.vscode/launch.json
  api/Dockerfile
  api/bin/console
  api/composer.json
  api/config/packages/api_platform.yaml
  api/config/packages/doctrine.yaml
  api/config/packages/framework.yaml
  api/config/packages/twig.yaml
  api/docker/caddy/Caddyfile
  api/docker/caddy/Caddyfile.prod
  api/docker/php/conf.d/api-platform.dev.ini
  api/docker/php/conf.d/api-platform.prod.ini
  api/docker/php/docker-entrypoint.sh
  api/docker/php/docker-healthcheck.sh
  api/docker/php/migrate-database.sh
  api/docker/php/php-fpm.d/www.conf
  api/docker/php/php-fpm.d/zz-docker.conf
  api/docker/varnish/vcl/_config.vcl
  api/phpunit.xml.dist
  api/symfony.lock
  api/tests/bootstrap.php
  api/var/.gitignore
  docker-compose.yml
  pre-commit.sh
  print/nuxt.config.js
Labels: deploy!

#5170 frontend: add simple part of vue/vue3-recommended rules
  frontend/package.json
  frontend/src/components/activity/DaySwitcher.vue
  frontend/src/components/activity/content/storyboard/StoryboardRowDefault.vue
  frontend/src/components/activity/content/storyboard/StoryboardRowDense.vue
  frontend/src/components/activity/content/storyboard/StoryboardSortable.vue
  frontend/src/components/dialog/DialogBottomSheet.vue
  frontend/src/components/dialog/DialogForm.vue
  frontend/src/components/form/base/ColorPicker/ColorSwatch.vue
  frontend/src/components/form/base/EColorPicker.vue
  frontend/src/components/form/base/EDatePicker.vue
  frontend/src/components/generic/DetailPane.vue
  frontend/src/components/navigation/SideBar.vue
  frontend/src/components/program/DialogActivityCreate.vue
  frontend/src/components/program/DialogActivityEdit.vue
  frontend/src/components/program/ScheduleEntries.vue
  frontend/src/components/program/picasso/Picasso.vue
  frontend/src/components/program/picasso/PicassoEntry.vue
  frontend/src/views/activity/SideBarProgram.vue
  frontend/src/views/camp/CampProgram.vue
Labels: deploy!

#5126 frontend: add lint rule for ":deep usage as a combinator has been deprecated"
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/activity/DraggableContentNodes.vue
  frontend/src/components/collaborator/CollaboratorForm.vue
  frontend/src/components/program/picasso/PicassoEntry.vue
  frontend/src/components/prompt/PopoverPrompt.vue
  frontend/src/views/Profile.vue
  frontend/src/views/auth/Login.vue
Labels: deploy!

#5278 fix: sentry error reporting for print-nuxt
  frontend/package-lock.json
  frontend/package.json
  print/package-lock.json
  print/package.json
  print/server/api/pdf.js
  print/server/plugins/sentry.ts
Labels: deploy!

#5292 fix api performance_test
  api/config/packages/performance_test/http_cache.yaml
  api/tests/Api/SnapshotTests/__snapshots__/performance_test_EndpointPerformanceTest__testPerformanceDidNotChangeForStableEndpoints__1.yml
Labels: api-performance-test!

#5288 Harmonize Y+S logo on all channels & add icons in settings
  common/assets/logos/GSLogo.svg
  common/assets/logos/JSLogo.svg
  frontend/src/components/campAdmin/CampActivityProgressLabels.vue
  frontend/src/components/campAdmin/CampAddress.vue
  frontend/src/components/campAdmin/CampCategories.vue
  frontend/src/components/campAdmin/CampConditionalFields.vue
  frontend/src/components/campAdmin/CampPeriods.vue
  frontend/src/components/campAdmin/CampSettings.vue
  frontend/src/components/layout/ContentGroup.vue
  frontend/src/plugins/vuetify.js
  pdf/src/campPrint/picasso/PicassoPage.vue
  pdf/src/renderer/__tests__/__snapshots__/picasso.spec.json.snap
  print/common
  print/components/PicassoChunk.vue
  print/components/PicassoPeriod.vue
  print/components/generic/CategoryLabel.vue
  print/components/generic/UserAvatar.vue
  print/components/generic/YSLogo.vue
  print/components/picasso/CalendarDay.vue
  print/components/picasso/CalendarDayHeader.vue
  print/components/picasso/ScheduleEntry.vue
  print/components/scheduleEntry/ScheduleEntry.vue
  print/locales/vueI18nConfig.js
  print/mixins/dateHelperUTCFormatted.js
  print/nuxt.config.js
  print/package-lock.json
  print/package.json
  print/plugins/dayjs.js
  print/vitest.config.ts
Labels: deploy!

#5317 fix PurgeHttpCacheListener
  api/src/HttpCache/PurgeHttpCacheListener.php
  api/tests/HttpCache/PurgeHttpCacheListenerTest.php
Labels: deploy!

#5285 TipTap Autolink: Show cursor on hover + meta/ctrl
  frontend/src/components/form/tiptap/TiptapEditor.vue
Labels: deploy!

#5281 Add custom color campcollaboration
  api/migrations/dev-data/data.sql
  api/migrations/prod-data/data.sql
  api/migrations/schema/Version20240507154923.php
  api/migrations/schema/Version20240619081247.php
  api/src/Entity/CampCollaboration.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetCollectionMatchesStructure with data set camp_collaborations__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetItemMatchesStructure with data set camp_collaborations__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetItemMatchesStructure with data set camps__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testOpenApiSpecMatchesSnapshot__1.yml
  common/helpers/__tests__/campCollaborationInitials.spec.js
  common/helpers/__tests__/colors.spec.js
  common/helpers/campCollaborationInitials.js
  common/helpers/colors.js
  common/locales/de.json
  common/locales/en.json
  common/locales/fr.json
  common/locales/it.json
  frontend/src/components/collaborator/CollaboratorCreate.vue
  frontend/src/components/collaborator/CollaboratorEdit.vue
  frontend/src/components/collaborator/CollaboratorForm.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/plugins/veeValidate.js
  frontend/src/plugins/veeValidate/__tests__/oneEmojiOrTwoCharacters.spec.js
  frontend/src/plugins/veeValidate/oneEmojiOrTwoCharacters.js
  frontend/src/views/dev/Controls.vue
  frontend/vite.config.js
Labels: deploy!

#5249 fix: add tests for observing purged tags + fix edge cases
  api/src/HttpCache/PurgeHttpCacheListener.php
  api/tests/Api/Categories/CreateCategoryTest.php
  api/tests/Api/Categories/DeleteCategoryTest.php
  api/tests/Api/Categories/UpdateCategoryTest.php
  api/tests/Api/ContentNodes/CreateContentNodeTestCase.php
  api/tests/Api/ECampApiTestCase.php
  api/tests/HttpCache/CacheManagerMock.php
  api/tests/HttpCache/PurgeHttpCacheListenerTest.php
Labels: test-flaky-e2e!, api-performance-test!

#5456 fix slot-name
  frontend/src/components/campAdmin/CampPeriods.vue
Labels: Bug

#5458 ZipCode and City on one line
  frontend/src/components/campAdmin/CampAddress.vue
Labels: deploy!
