Repository ecamp/ecamp3, pull requests merged in 2024-03, with the labels that each got.

#4745 api: restrict access to protected routes with firewall
  api/config/packages/security.yaml
  api/src/Util/ParametrizedTestHelper.php
  api/tests/Api/FirewallTest.php
  api/tests/Api/Invitations/AcceptInvitationTest.php
  api/tests/Api/Invitations/InvitationGraphQLTest.php
  api/tests/Api/Profiles/ReadProfileTest.php
  api/tests/Api/Profiles/UpdateProfileTest.php
  api/tests/Api/Users/ReadUserTest.php
Labels: deploy!

#4753 Correctly check inclusion in array
  frontend/src/components/print/config/PicassoConfig.vue
Labels: deploy!

#4761 Bugfix: Prevent wrong dirty reset
  frontend/src/components/form/api/ApiRichtext.vue
  frontend/src/components/form/api/ApiTextField.vue
  frontend/src/components/form/api/ApiTextarea.vue
  frontend/src/components/form/api/ApiWrapper.vue
  frontend/src/components/form/api/__tests__/ApiWrapper.spec.js
Labels: Bug, deploy!, External feedback

#4764 Fix printing in languages other than English
  frontend/src/components/print/PrintConfigurator.vue
  frontend/src/components/print/__tests__/repairPrintConfig.spec.js
  frontend/src/components/print/print-client/i18n.js
  frontend/src/components/print/repairPrintConfig.js
Labels: deploy!

#4618 Add help & news on login screen and main nav
  .github/workflows/reusable-dev-deployment.yml
  .github/workflows/reusable-stage-prod-deployment.yml
  .helm/deploy-to-cluster.sh
  .helm/ecamp3/templates/frontend_configmap.yaml
  .helm/ecamp3/values.yaml
  frontend/src/App.vue
  frontend/src/components/layout/AuthContainer.vue
  frontend/src/components/navigation/UserMeta.vue
  frontend/src/environment.js
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/locales/rm.json
  frontend/src/router.js
  frontend/src/views/NavigationDefault.vue
  frontend/src/views/Profile.vue
  frontend/src/views/auth/NavigationAuth.vue
  frontend/src/views/camp/navigation/desktop/NavTopbar.vue
  frontend/src/views/camp/navigation/mobile/NavSidebar.vue
Labels: type: Frontend, UX/UI, deploy!

#4832 Fix sidebar meta links on mobile
  frontend/src/components/layout/SidebarListItem.vue
  frontend/src/views/camp/navigation/mobile/NavSidebar.vue
Labels: Bug, deploy!

#4826 Autofocus and autoselect title of new activity
  frontend/src/components/program/DialogActivityCreate.vue
  frontend/src/components/program/DialogActivityForm.vue
Labels: deploy!

#4823 Copy category from other category or from activity
  api/src/Entity/Activity.php
  api/src/Entity/Category.php
  api/src/State/CategoryCreateProcessor.php
  api/tests/Api/Categories/CreateCategoryTest.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testOpenApiSpecMatchesSnapshot__1.yml
  frontend/src/components/activity/ScheduleEntry.vue
  frontend/src/components/campAdmin/DialogCategoryCreate.vue
  frontend/src/components/campAdmin/DialogCategoryForm.vue
  frontend/src/components/category/CopyCategoryInfoDialog.vue
  frontend/src/components/program/DialogActivityCreate.vue
  frontend/src/components/program/picasso/PicassoEntry.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/views/category/Category.vue
Labels: deploy!
