Repository ecamp/ecamp3, pull requests merged in 2024-04, with the labels that each got.

#4817 feat(print-nuxt): auto-grow picasso instead of fixed height
  print/assets/calendar/CalendarDaily.sass
  print/components/PicassoChunk.vue
  print/components/picasso/Calendar.vue
  print/components/picasso/CalendarDay.vue
Labels: deploy!

#4932 Move invitations to separate view
  frontend/src/components/navigation/UserMeta.vue
  frontend/src/components/personal_invitations/DialogPersonalInvitationReject.vue
  frontend/src/components/personal_invitations/PersonalInvitations.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/locales/rm.json
  frontend/src/router.js
  frontend/src/views/Camps.vue
  frontend/src/views/Invitations.vue
Labels: deploy!

#4941 Fix small issues with invitation badges from testing on staging
  frontend/src/components/navigation/UserMeta.vue
  frontend/src/components/personal_invitations/DialogPersonalInvitationReject.vue
Labels: deploy!

#4738 api: add performance_test environment which loads more data
  .github/workflows/api-performance-test.yml
  .github/workflows/reusable-api-performance-test.yml
  api/.env.performance_test
  api/composer.json
  api/config/bundles.php
  api/config/packages/framework.yaml
  api/config/packages/performance_test/doctrine.yaml
  api/config/packages/performance_test/doctrine_migrations.yaml
  api/config/packages/performance_test/hautelook_alice.yaml
  api/config/packages/performance_test/mailer.yaml
  api/config/packages/performance_test/monolog.yaml
  api/config/packages/performance_test/nelmio_alice.yaml
  api/config/packages/performance_test/routing.yaml
  api/config/packages/performance_test/validator.yaml
  api/config/packages/performance_test/web_profiler.yaml
  api/config/packages/security.yaml
  api/fixtures/performance_test/activities.yml
  api/fixtures/performance_test/activity-progress-labels.yml
  api/fixtures/performance_test/activityResponsibles.yml
  api/fixtures/performance_test/campCollaborations.yml
  api/fixtures/performance_test/camps.yml
  api/fixtures/performance_test/categories.yml
  api/fixtures/performance_test/columnLayouts.yml
  api/fixtures/performance_test/dayResponsibles.yml
  api/fixtures/performance_test/days.yml
  api/fixtures/performance_test/materialItems.yml
  api/fixtures/performance_test/materialLists.yml
  api/fixtures/performance_test/periods.yml
  api/fixtures/performance_test/profiles.yml
  api/fixtures/performance_test/responsiveLayouts.yml
  api/fixtures/performance_test/users.yml
  api/phpunit.performance_test.xml.dist
  api/tests/Api/SnapshotTests/EndpointPerformanceTest.php
  api/tests/Api/SnapshotTests/__snapshots__/performance_test_EndpointPerformanceTest__testPerformanceDidNotChangeForStableEndpoints__1.yml
  api/tests/Api/SnapshotTests/__snapshots__/test_EndpointPerformanceTest__testPerformanceDidNotChangeForStableEndpoints__1.yml
Labels: api-performance-test!

#4573 Implement picasso filters
  frontend/package.json
  frontend/src/components/layout/ContentCard.vue
  frontend/src/components/program/PeriodSwitcher.vue
  frontend/src/components/program/ScheduleEntries.vue
  frontend/src/components/program/ScheduleEntryFilters.vue
  frontend/src/components/program/picasso/Picasso.vue
  frontend/src/components/program/picasso/PicassoEntry.vue
  frontend/src/components/program/picasso/useDragAndDropMove.js
  frontend/src/components/program/picasso/useDragAndDropResize.js
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/locales/rm.json
  frontend/src/views/camp/CampProgram.vue
  frontend/src/views/camp/Dashboard.vue
Labels: deploy!

#4940 chore(performance): use subresources & uriTemplate property to avoid …
  api/src/Entity/Day.php
  api/src/Entity/DayResponsible.php
  api/src/Entity/Period.php
  api/src/Entity/ScheduleEntry.php
  api/tests/Api/DayResponsibles/ListDayResponsiblesTest.php
  api/tests/Api/Days/ListDaysTest.php
  api/tests/Api/Days/ReadDayTest.php
  api/tests/Api/Periods/ReadPeriodTest.php
  api/tests/Api/ScheduleEntries/ListScheduleEntriesTest.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testOpenApiSpecMatchesSnapshot__1.yml
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testRootEndpointMatchesSnapshot__1.json
  api/tests/Api/SnapshotTests/__snapshots__/performance_test_EndpointPerformanceTest__testPerformanceDidNotChangeForStableEndpoints__1.yml
  api/tests/Api/SnapshotTests/__snapshots__/test_EndpointPerformanceTest__testPerformanceDidNotChangeForStableEndpoints__1.yml
Labels: deploy!

#4500 feat: Edit schedule entries from activity view
  common/locales/de.json
  frontend/src/components/activity/ScheduleEntry.vue
  frontend/src/components/activity/dialog/DialogActivityEdit.vue
  frontend/src/components/activity/dialog/DialogActivityForm.vue
  frontend/src/components/activity/dialog/FormScheduleEntryItem.vue
  frontend/src/components/activity/dialog/FormScheduleEntryList.vue
  frontend/src/components/generic/DetailPane.vue
  frontend/src/components/program/DialogActivityCreate.vue
  frontend/src/components/program/ScheduleEntries.vue
  frontend/src/components/program/picasso/PicassoEntry.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/locales/rm.json
  frontend/src/scss/global.scss
Labels: deploy!

#4967 Revert "feat: Edit schedule entries from activity view"
  common/locales/de.json
  frontend/src/components/activity/ScheduleEntry.vue
  frontend/src/components/generic/DetailPane.vue
  frontend/src/components/program/DialogActivityCreate.vue
  frontend/src/components/program/DialogActivityEdit.vue
  frontend/src/components/program/DialogActivityForm.vue
  frontend/src/components/program/FormScheduleEntryItem.vue
  frontend/src/components/program/FormScheduleEntryList.vue
  frontend/src/components/program/ScheduleEntries.vue
  frontend/src/components/program/picasso/PicassoEntry.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/locales/rm.json
  frontend/src/scss/global.scss
Labels: deploy!

#4987 reusable-api-performance-test.yml: run with only 1 cpu and 1G memory
  .github/workflows/reusable-api-performance-test.yml
Labels: api-performance-test!

#4981 Move dev info to /debug
  frontend/src/App.vue
  frontend/src/assets/icons/Coffee.vue
  frontend/src/router.js
  frontend/src/views/dev/Debug.vue
Labels: deploy!

#5019 Fixes missing function call
  frontend/src/components/user/UserAvatar.vue
Labels: deploy!

#4959 EndpointPerformanceTest: add collection endpoints with filter
  api/tests/Api/SnapshotTests/EndpointPerformanceTest.php
  api/tests/Api/SnapshotTests/__snapshots__/performance_test_EndpointPerformanceTest__testPerformanceDidNotChangeForStableEndpoints__1.yml
  api/tests/Api/SnapshotTests/__snapshots__/test_EndpointPerformanceTest__testPerformanceDidNotChangeForStableEndpoints__1.yml
Labels: api-performance-test!

#4990 Add new singleText content types for courses
  api/fixtures/contentTypes.yml
  api/migrations/schema/Version20240416120000.php
  api/tests/Api/ContentTypes/ListContentTypesTest.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetCollectionMatchesStructure with data set content_types__1.json
  common/locales/de.json
  common/locales/en.json
  frontend/src/components/activity/ContentNode.vue
  frontend/src/components/activity/content/LearningObjectives.vue
  frontend/src/components/activity/content/LearningTopics.vue
  pdf/src/campPrint/scheduleEntry/contentNode/ContentNode.vue
  pdf/src/campPrint/scheduleEntry/contentNode/LearningObjectives.vue
  pdf/src/campPrint/scheduleEntry/contentNode/LearningTopics.vue
  print/components/scheduleEntry/contentNode/ContentNode.vue
  print/components/scheduleEntry/contentNode/LearningObjectives.vue
  print/components/scheduleEntry/contentNode/LearningTopics.vue
Labels: deploy!

#5026 Add offline message
  frontend/src/App.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/locales/rm.json
Labels: deploy!

#5000 Database Query Performance
  api/config/packages/doctrine.yaml
  api/migrations/schema/Version20240414092957.php
  api/src/Doctrine/Filter/ContentNodePeriodFilter.php
  api/src/Doctrine/Filter/MaterialItemPeriodFilter.php
  api/src/Doctrine/QueryBuilderHelper.php
  api/src/Entity/Camp.php
  api/src/Entity/User.php
  api/src/Entity/UserCamp.php
  api/src/Repository/ActivityProgressLabelRepository.php
  api/src/Repository/ActivityRepository.php
  api/src/Repository/ActivityResponsibleRepository.php
  api/src/Repository/CampCollaborationRepository.php
  api/src/Repository/CategoryRepository.php
  api/src/Repository/DayRepository.php
  api/src/Repository/DayResponsibleRepository.php
  api/src/Repository/FiltersByCampCollaboration.php
  api/src/Repository/FiltersByContentNode.php
  api/src/Repository/MaterialItemRepository.php
  api/src/Repository/MaterialListRepository.php
  api/src/Repository/PeriodRepository.php
  api/src/Repository/ScheduleEntryRepository.php
  api/tests/Doctrine/Filter/ContentNodePeriodFilterTest.php
Labels: deploy!, api-performance-test!

#5025 Remove unnecessary function calls and this.api bindings in router.js
  frontend/src/components/activity/DaySwitcher.vue
  frontend/src/components/activity/ScheduleEntry.vue
  frontend/src/components/activity/content/Material.vue
  frontend/src/components/campAdmin/CampActivityProgressLabels.vue
  frontend/src/components/campAdmin/CampAddress.vue
  frontend/src/components/campAdmin/CampCategories.vue
  frontend/src/components/campAdmin/CampConditionalFields.vue
  frontend/src/components/campAdmin/CampDangerZone.vue
  frontend/src/components/campAdmin/CampMaterialLists.vue
  frontend/src/components/campAdmin/CampPeriods.vue
  frontend/src/components/campAdmin/CampSettings.vue
  frontend/src/components/material/DialogMaterialItemCreate.vue
  frontend/src/components/material/DialogMaterialItemEdit.vue
  frontend/src/components/material/DialogMaterialItemForm.vue
  frontend/src/components/material/MaterialLists.vue
  frontend/src/components/material/useMaterialViewHelper.js
  frontend/src/components/print/PrintConfigurator.vue
  frontend/src/components/program/DialogActivityCreate.vue
  frontend/src/components/program/DialogActivityEdit.vue
  frontend/src/components/program/DialogActivityForm.vue
  frontend/src/components/program/FormScheduleEntryList.vue
  frontend/src/components/program/PeriodSwitcher.vue
  frontend/src/components/program/ScheduleEntries.vue
  frontend/src/components/program/ScheduleEntryFilters.vue
  frontend/src/router.js
  frontend/src/views/activity/Activity.vue
  frontend/src/views/activity/SideBarProgram.vue
  frontend/src/views/admin/Activity.vue
  frontend/src/views/admin/AdminMaterialLists.vue
  frontend/src/views/admin/Collaborators.vue
  frontend/src/views/admin/Info.vue
  frontend/src/views/admin/Print.vue
  frontend/src/views/admin/SideBarAdmin.vue
  frontend/src/views/admin/__tests__/Admin.spec.js
  frontend/src/views/camp/Admin.vue
  frontend/src/views/camp/CampProgram.vue
  frontend/src/views/camp/Dashboard.vue
  frontend/src/views/camp/Invitation.vue
  frontend/src/views/camp/Story.vue
  frontend/src/views/camp/navigation/NavigationCamp.vue
  frontend/src/views/camp/navigation/desktop/NavTopbar.vue
  frontend/src/views/camp/navigation/mobile/NavBottombar.vue
  frontend/src/views/camp/navigation/mobile/NavSidebar.vue
  frontend/src/views/category/Category.vue
  frontend/src/views/category/SideBarCategory.vue
  frontend/src/views/material/MaterialDetail.vue
  frontend/src/views/material/MaterialLists.vue
  frontend/src/views/material/MaterialOverview.vue
  frontend/src/views/material/SideBarMaterialLists.vue
Labels: deploy!, test-flaky-e2e!
