Repository ecamp/ecamp3, pull requests merged in 2024-08, with the labels that each got.

#5539 Bugfix: sort periods (picasso, story, admin)
  frontend/src/components/campAdmin/CampPeriods.vue
  frontend/src/components/program/PeriodSwitcher.vue
Labels: Bug, deploy!

#5535 Sort campCollaboration- & MaterialList-List
  common/helpers/__tests__/materialListsSorted.spec.js
  common/helpers/materialListsSorted.js
  frontend/src/components/activity/ActivityResponsibles.vue
  frontend/src/components/collaborator/CollaboratorList.vue
  frontend/src/components/material/MaterialCreateItem.vue
  frontend/src/components/material/MaterialLists.vue
  frontend/src/components/material/MaterialListsEdit.vue
  frontend/src/components/program/ScheduleEntryFilters.vue
Labels: deploy!

#5579 materialItem: validate that quantity is greater than 0
  api/src/Entity/MaterialItem.php
  api/tests/Api/MaterialItems/CreateMaterialItemTest.php
  api/tests/Api/MaterialItems/UpdateMaterialItemTest.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testOpenApiSpecMatchesSnapshot__1.yml
  frontend/src/components/material/DialogMaterialItemForm.vue
  frontend/src/components/material/MaterialCreateItem.vue
  frontend/src/components/material/MaterialTable.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/plugins/veeValidate.js
  frontend/src/plugins/veeValidate/__tests__/greaterThan.spec.js
  frontend/src/plugins/veeValidate/greaterThan.js
Labels: deploy!

#5669 Rename safety concept to safety considerations
  api/fixtures/activity1-aside-top.yml
  api/fixtures/categories.yml
  api/fixtures/contentTypes.yml
  api/fixtures/performance_test/activities.yml
  api/fixtures/performance_test/categories.yml
  api/migrations/schema/Version20240817181500.php
  api/src/Entity/ContentNode.php
  api/src/Entity/ContentType.php
  api/tests/Api/Categories/CreateCategoryTest.php
  api/tests/Api/Categories/UpdateCategoryTest.php
  api/tests/Api/ContentNodes/ContentNode/ListContentNodesTest.php
  api/tests/Api/ContentNodes/CreateContentNodeTestCase.php
  api/tests/Api/ContentNodes/SingleText/ListSingleTextTest.php
  api/tests/Api/ContentTypes/DeleteContentTypeTest.php
  api/tests/Api/ContentTypes/ReadContentTypeTest.php
  api/tests/Api/ContentTypes/UpdateContentTypeTest.php
  api/tests/Api/SnapshotTests/ReadItemFixtureMap.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testOpenApiSpecMatchesSnapshot__1.yml
  common/locales/de.json
  common/locales/en.json
  common/locales/fr.json
  common/locales/it.json
  e2e/specs/responses/content_types_collection.json
  frontend/src/components/activity/ContentNode.vue
  frontend/src/components/activity/content/SafetyConsiderations.vue
  pdf/src/campPrint/scheduleEntry/contentNode/ContentNode.vue
  pdf/src/campPrint/scheduleEntry/contentNode/SafetyConsiderations.vue
  pdf/src/renderer/__tests__/__snapshots__/program.spec.json.snap
  pdf/src/renderer/__tests__/__snapshots__/single_activity.spec.json.snap
  pdf/src/renderer/__tests__/fullCampStoreContent.json
  print/components/scheduleEntry/contentNode/ContentNode.vue
  print/components/scheduleEntry/contentNode/SafetyConsiderations.vue
Labels: deploy!

#5785 Fix new phpstan lint error
  api/src/Doctrine/Filter/ExpressionDateTimeFilter.php
Labels: Bug, Blocks others

#5779 simplify test user login
  frontend/src/views/auth/Login.vue
Labels: deploy!

#5560 use api prod image for e2e tests
  .github/workflows/reusable-e2e-tests-build.yml
  .github/workflows/reusable-e2e-tests-run.yml
  .helm/ecamp3/templates/api_deployment.yaml
  api/.env
  api/Dockerfile
  api/config/packages/dev/lexik_jwt_authentication.yaml
  api/config/packages/lexik_jwt_authentication.yaml
  api/docker/caddy/Caddyfile
  api/docker/caddy/Caddyfile.prod
  api/docker/varnish/vcl/_config.vcl
  api/docker/varnish/vcl/default.vcl
  docker-compose.override.yml
  docker-compose.yml
  e2e/README.md
  print/print.env
  reverse-proxy-nginx.conf
Labels: deploy!
