Repository ecamp/ecamp3, pull requests merged in 2025-04, with the labels that each got.

#7085 reverse-proxy-nginx.conf: use upstreams for the proxy_pass directives
  reverse-proxy-nginx.conf
Labels: deploy!

#7115 Performance: ContentNodeCampFilter, remove unnecessary joins
  api/src/Doctrine/Filter/ContentNodeCampFilter.php
Labels: Performance

#7114 Performance: /api/content_node/checklist_nodes
  api/migrations/schema/Version20250324224924.php
  api/src/Entity/ContentNode.php
  api/tests/Api/ContentNodes/RootColumnLayout/CreateRootColumnLayoutTest.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testOpenApiSpecMatchesSnapshot__1.yml
Labels: Performance

#7051 Performance: Reuse existing joins in QueryBuilder
  api/src/Repository/ActivityResponsibleRepository.php
  api/src/Repository/DayRepository.php
  api/src/Repository/DayResponsibleRepository.php
  api/src/Repository/FiltersByCampCollaboration.php
  api/src/Repository/MaterialItemRepository.php
  api/src/Repository/ScheduleEntryRepository.php
  api/src/Util/QueryBuilderHelper.php
  api/tests/Util/QueryBuilderHelperTest.php
Labels: deploy!, Performance

#7135 CampCollaboration do not embed Camp
  api/src/Entity/CampCollaboration.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetItemMatchesStructure with data set camp_collaborations__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testOpenApiSpecMatchesSnapshot__1.yml
  api/tests/Api/SnapshotTests/__snapshots__/test_EndpointPerformanceTest__testPerformanceDidNotChangeForStableEndpoints__1.yml
Labels: Performance

#7192 chore: change varnish log output to escapedUrl format
  .helm/ecamp3/values.yaml
Labels: deploy!

#7193 activity & category, do not embed rootContentNode
  api/src/Entity/HasRootContentNodeTrait.php
  api/tests/Api/Activities/ReadActivityTest.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetCollectionMatchesStructure with data set activities__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetCollectionMatchesStructure with data set categories__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetItemMatchesStructure with data set activities__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetItemMatchesStructure with data set categories__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetItemMatchesStructure with data set schedule_entries__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testOpenApiSpecMatchesSnapshot__1.yml
  api/tests/Api/SnapshotTests/__snapshots__/test_EndpointPerformanceTest__testPerformanceDidNotChangeForStableEndpoints__1.yml
  e2e/specs/httpCache/categories.cy.js
  e2e/specs/httpCache/responses/categories_collection.json
Labels: deploy!

#7206 Adjust title tag to match view
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/activity/ScheduleEntry.vue
  frontend/src/main.js
  frontend/src/plugins/head.js
  frontend/src/plugins/index.js
  frontend/src/views/CampCreate.vue
  frontend/src/views/Camps.vue
  frontend/src/views/Invitations.vue
  frontend/src/views/PageNotFound.vue
  frontend/src/views/Profile.vue
  frontend/src/views/camp/CampProgram.vue
  frontend/src/views/camp/Dashboard.vue
  frontend/src/views/camp/Invitation.vue
  frontend/src/views/camp/Story.vue
  frontend/src/views/camp/admin/Activity.vue
  frontend/src/views/camp/admin/AdminMaterialLists.vue
  frontend/src/views/camp/admin/Checklists.vue
  frontend/src/views/camp/admin/Collaborators.vue
  frontend/src/views/camp/admin/Info.vue
  frontend/src/views/camp/admin/Print.vue
  frontend/src/views/camp/category/Category.vue
  frontend/src/views/camp/checklistOverview/ChecklistLists.vue
  frontend/src/views/camp/checklistOverview/ChecklistOverview.vue
  frontend/src/views/camp/material/MaterialDetail.vue
  frontend/src/views/camp/material/MaterialOverview.vue
Labels: deploy!

#7198 chore: sync updates from upstream template api-platform/api-platform
  api/Dockerfile
  api/composer.json
  api/composer.lock
  api/config/packages/doctrine.yaml
  api/config/packages/framework.yaml
  api/config/packages/validator.yaml
  api/docker/caddy/Caddyfile
  api/tests/HttpCache/PurgeHttpCacheListenerTest.php
Labels: deploy!

#7219 Add title tag to auth & dev pages
  frontend/src/plugins/head.js
  frontend/src/views/auth/Activate.vue
  frontend/src/views/auth/Login.vue
  frontend/src/views/auth/Register.vue
  frontend/src/views/auth/ResetPassword.vue
  frontend/src/views/auth/ResetPasswordRequest.vue
  frontend/src/views/camp/CampProgram.vue
  frontend/src/views/camp/Dashboard.vue
  frontend/src/views/camp/Story.vue
  frontend/src/views/camp/admin/Activity.vue
  frontend/src/views/camp/admin/AdminMaterialLists.vue
  frontend/src/views/camp/admin/Checklists.vue
  frontend/src/views/camp/admin/Collaborators.vue
  frontend/src/views/camp/admin/Info.vue
  frontend/src/views/camp/admin/Print.vue
  frontend/src/views/camp/category/Category.vue
  frontend/src/views/camp/checklistOverview/ChecklistLists.vue
  frontend/src/views/camp/checklistOverview/ChecklistOverview.vue
  frontend/src/views/camp/material/MaterialDetail.vue
  frontend/src/views/camp/material/MaterialOverview.vue
  frontend/src/views/camp/navigation/NavigationCamp.vue
  frontend/src/views/dev/Controls.vue
  frontend/src/views/dev/Performance.vue
Labels: deploy!

#7217 MaterialItem.MaterialList is nullable
  api/migrations/schema/Version20250412165829.php
  api/src/Entity/ContentNode.php
  api/src/Entity/MaterialItem.php
  api/src/Repository/MaterialItemRepository.php
  api/src/State/ActivityCreateProcessor.php
  api/src/State/CampCreateProcessor.php
  api/src/State/CategoryCreateProcessor.php
  api/src/State/ChecklistCreateProcessor.php
  api/src/Util/EntityMap.php
  api/tests/Api/Activities/CreateActivityTest.php
  api/tests/Api/MaterialItems/CreateMaterialItemTest.php
  api/tests/Api/MaterialItems/UpdateMaterialItemTest.php
  api/tests/Api/SnapshotTests/EndpointPerformanceTest.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetCollectionMatchesStructure with data set content_nodematerial_nodes__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetCollectionMatchesStructure with data set content_nodes__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetCollectionMatchesStructure with data set material_items__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetItemMatchesStructure with data set activities__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetItemMatchesStructure with data set material_items__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testOpenApiSpecMatchesSnapshot__1.yml
  api/tests/Api/SnapshotTests/__snapshots__/test_EndpointPerformanceTest__testPerformanceDidNotChangeForStableEndpoints__1.yml
  api/tests/Entity/CampTest.php
  api/tests/Security/Voter/CampIsPrototypeVoterTest.php
  api/tests/Security/Voter/CampRoleVoterTest.php
  frontend/src/components/material/DialogMaterialItemEdit.vue
  frontend/src/components/material/MaterialTable.vue
  pdf/src/campPrint/scheduleEntry/contentNode/Material.vue
  print/components/scheduleEntry/contentNode/Material.vue
Labels: deploy!
