Repository ecamp/ecamp3, pull requests merged in 2025-10, with the labels that each got.

#7226 Add basic comments UI (behind feature toggle)
  frontend/src/components/comments/Comment.vue
  frontend/src/components/comments/CommentWrapper.vue
  frontend/src/components/comments/Comments.vue
  frontend/src/environment.js
  frontend/src/views/camp/activity/Activity.vue
Labels: before-vue3

#7641 fix n+1 api-requests on admin/checklist
  frontend/src/components/checklist/ChecklistItemEdit.vue
Labels: deploy!, before-vue3

#7956 MaterialItem Done-Checkbox, API
  api/migrations/schema/Version20251003000000.php
  api/src/Entity/MaterialItem.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetCollectionMatchesStructure with data set content_nodematerial_nodes__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetCollectionMatchesStructure with data set content_nodes__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetCollectionMatchesStructure with data set material_items__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetItemMatchesStructure with data set activities__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetItemMatchesStructure with data set material_items__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testOpenApiSpecMatchesSnapshot__1.yml
Labels: before-vue3

#8280 ContentNodes-Endpoint requires filter on camp or period.
  api/config/services.yaml
  api/src/Entity/ContentNode.php
  api/src/State/ContentNodeCollectionProvider.php
  api/tests/Api/ContentNodes/ContentNode/ListContentNodesTest.php
  api/tests/Api/SnapshotTests/EndpointPerformanceTest.php
  api/tests/Api/SnapshotTests/ResponseSnapshotTest.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetCollectionMatchesStructure with data set content_nodes__1.json
Labels: deploy!
