Repository ecamp/ecamp3, pull requests merged in 2025-03, with the labels that each got.

#5495 Add timefield
  common/helpers/dayjs.js
  common/helpers/dayjs/__tests__/parseTime.spec.js
  common/helpers/dayjs/parseTime.js
  frontend/src/components/form/base/ETimeField.vue
  frontend/src/components/form/base/__tests__/ETimeField.spec.js
  frontend/src/views/dev/Controls.vue
Labels: deploy!

#6949 api: cache root endpoint
  api/config/packages/http_cache.yaml
  api/tests/CacheRegexTest.php
Labels: deploy!

#6955 Fix racing bug on slow network
  frontend/src/components/form/api/ApiWrapper.vue
Labels: Bug, deploy!

#6956 Performance improvements
  api/src/Entity/Profile.php
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetCollectionMatchesStructure with data set profiles__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testGetItemMatchesStructure with data set profiles__1.json
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testOpenApiSpecMatchesSnapshot__1.yml
  api/tests/Api/SnapshotTests/__snapshots__/ResponseSnapshotTest__testRootEndpointMatchesSnapshot__1.json
  frontend/src/components/camp/CampListItem.vue
  frontend/src/components/navigation/UserMeta.vue
  frontend/src/plugins/__tests__/auth.spec.js
  frontend/src/plugins/auth.js
  frontend/src/views/Camps.vue
  frontend/src/views/camp/Dashboard.vue
Labels: deploy!, test-flaky-e2e!

#7048 Fix stale activity dom state
  frontend/src/components/activity/ScheduleEntry.vue
Labels: Bug, deploy!, External feedback

#7049 Revert "chore(deps): update dependency nuxt to v3.16.0"
  print/package-lock.json
  print/package.json
Labels: deploy!

#6997 Improve schedule entry picker
  common/helpers/__tests__/dateHelperUTCFormatted.spec.js
  common/helpers/dateHelperUTCFormatted.js
  common/locales/de.json
  common/locales/en.json
  common/locales/fr.json
  frontend/src/components/activity/dialog/FormScheduleEntryItem.vue
  frontend/src/components/activity/dialog/FormScheduleEntryList.vue
  frontend/src/components/form/base/EParseField.vue
  frontend/src/components/form/base/ETimeDropdown.vue
  frontend/src/components/form/base/ETimeField.vue
  frontend/src/scss/tailwind.scss
Labels: deploy!
